### ISSUE TITLE
foreground/console do not import /etc/<pkg>/<pkg>.config

### ISSUE THREAD

**Issue by opie4624** [arjan/pkgx#1]
For example, with a package named `hcw` when I run `/etc/init.d/hcw foreground`:

```
Exec: /usr/lib/erlang/erts-6.3/bin/erlexec -noshell -noinput +Bd -boot /usr/lib/hcw/releases/0.0.1/hcw -mode embedded -config /usr/lib/hcw/releases/0.0.1/sys.config -boot_var ERTS_LIB_DIR /usr/lib/erlang/erts-6.3/../lib -args_file /usr/lib/hcw/releases/0.0.1/vm.args -- foreground
Root: /usr/lib/hcw
```

**Comment by arjan** [comment]
Are you saying it _does not_ or it _should not_ import <pkg>.config?

**Comment by eshubin** [comment]
Erlang node is launched with config file from release "-config /usr/lib/hcw/releases/0.0.1/sys.config", although it should be launched with "-config /etc/hcw/hcw.config".
Likely the error is here https://github.com/arjan/pkgx/blob/master/templates/deb_debian_init.dtl#L14.
relx uses RELX_CONFIG_PATH rather than CONFIG_PATH.

**Comment by arjan** [comment]
Thanks. I finally fixed this.
